import { PageHeader } from "@/components/page-header";
import { createLesson } from "@/app/dashboard/lms/actions";
import { getVisibleClassesForLearning, getVisibleSubjects } from "@/lib/lms";
import { canManageLms } from "@/lib/rbac";
import { getRequiredCurrentUser } from "@/lib/session";

export default async function NewLessonPage() { const user = await getRequiredCurrentUser(); if (!canManageLms(user.role)) return <PageHeader eyebrow="LMS" title="Not authorized" description="You cannot create lessons." />; const [classes, subjects] = await Promise.all([getVisibleClassesForLearning(user), getVisibleSubjects(user)]); return <div className="space-y-6 pb-10"><PageHeader eyebrow="LMS" title="Create Lesson" description="Create a persisted lesson for a permitted class and subject." /><LessonForm action={createLesson} classes={classes} subjects={subjects} /></div>; }
function LessonForm({ action, classes, subjects }: { action: (formData: FormData) => Promise<void>; classes: { id: string; name: string }[]; subjects: { id: string; name: string }[] }) { return <form action={action} className="space-y-4 rounded-lg border border-line bg-white p-5 shadow-soft"><div className="grid gap-4 sm:grid-cols-2"><Select name="classId" label="Class" options={classes} /><Select name="subjectId" label="Subject" options={subjects} /><Input name="title" label="Title" required /><Input name="description" label="Description" /></div><label className="block text-sm font-semibold text-ink">Content<textarea name="content" rows={8} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm" /></label><button className="rounded-md bg-ink px-5 py-3 text-sm font-bold text-white">Create Lesson</button>{classes.length === 0 || subjects.length === 0 ? <p className="text-sm text-moss">A real class and subject are required before lesson creation.</p> : null}</form>; }
function Select({ name, label, options }: { name: string; label: string; options: { id: string; name: string }[] }) { return <label className="text-sm font-semibold text-ink">{label}<select name={name} required className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm"><option value="">Choose {label.toLowerCase()}</option>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>; }
function Input({ name, label, required }: { name: string; label: string; required?: boolean }) { return <label className="text-sm font-semibold text-ink">{label}<input name={name} required={required} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm" /></label>; }
