import { notFound, redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { updateLesson, deleteLesson } from "@/app/dashboard/lms/actions";
import { getLessonForUser, getVisibleClassesForLearning, getVisibleSubjects } from "@/lib/lms";
import { canManageLms } from "@/lib/rbac";
import { getRequiredCurrentUser } from "@/lib/session";

export default async function EditLessonPage({ params }: { params: Promise<{ lessonId: string }> }) { const { lessonId } = await params; const user = await getRequiredCurrentUser(); if (!canManageLms(user.role)) redirect("/dashboard/lms"); const [lesson, classes, subjects] = await Promise.all([getLessonForUser(user, lessonId), getVisibleClassesForLearning(user), getVisibleSubjects(user)]); if (!lesson) notFound(); return <div className="space-y-6 pb-10"><PageHeader eyebrow="LMS" title="Edit Lesson" description="Update lesson details or delete the lesson." /><form action={updateLesson} className="space-y-4 rounded-lg border border-line bg-white p-5 shadow-soft"><input type="hidden" name="id" value={lesson.id} /><div className="grid gap-4 sm:grid-cols-2"><Select name="classId" label="Class" options={classes} defaultValue={lesson.classId} /><Select name="subjectId" label="Subject" options={subjects} defaultValue={lesson.subjectId} /><Input name="title" label="Title" defaultValue={lesson.title} required /><Input name="description" label="Description" defaultValue={lesson.description || ""} /></div><label className="block text-sm font-semibold text-ink">Content<textarea name="content" defaultValue={lesson.content || ""} rows={8} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm" /></label><button className="rounded-md bg-ink px-5 py-3 text-sm font-bold text-white">Save Lesson</button></form><form action={deleteLesson}><input type="hidden" name="id" value={lesson.id} /><button className="rounded-md border border-[#8b2b20] px-4 py-2 text-sm font-bold text-[#8b2b20]">Delete Lesson</button></form></div>; }
function Select({ name, label, options, defaultValue }: { name: string; label: string; options: { id: string; name: string }[]; defaultValue: string }) { return <label className="text-sm font-semibold text-ink">{label}<select name={name} required defaultValue={defaultValue} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm">{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>; }
function Input({ name, label, defaultValue, required }: { name: string; label: string; defaultValue?: string; required?: boolean }) { return <label className="text-sm font-semibold text-ink">{label}<input name={name} defaultValue={defaultValue} required={required} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm" /></label>; }
