import { PageHeader } from "@/components/page-header";
import { createAssignment } from "@/app/dashboard/assignments/actions";
import { getVisibleClassesForLearning, getVisibleSubjects } from "@/lib/lms";
import { canManageGrades } from "@/lib/rbac";
import { getRequiredCurrentUser } from "@/lib/session";

export default async function NewAssignmentPage() { const user = await getRequiredCurrentUser(); if (!canManageGrades(user.role)) return <PageHeader eyebrow="Assignments" title="Not authorized" description="You cannot create assignments." />; const [classes, subjects] = await Promise.all([getVisibleClassesForLearning(user), getVisibleSubjects(user)]); return <div className="space-y-6 pb-10"><PageHeader eyebrow="Assignments" title="Create Assignment" description="Create a class assignment and choose draft or published status." /><AssignmentForm action={createAssignment} classes={classes} subjects={subjects} /></div>; }
export function AssignmentForm({ action, classes, subjects, assignment }: { action: (formData: FormData) => Promise<void>; classes: { id: string; name: string }[]; subjects: { id: string; name: string }[]; assignment?: { id: string; classId: string; subjectId: string; title: string; description: string | null; dueDate: Date | null; maxPoints: number; status: string } }) { return <form action={action} className="space-y-4 rounded-lg border border-line bg-white p-5 shadow-soft"><input type="hidden" name="id" value={assignment?.id || ""} /><div className="grid gap-4 sm:grid-cols-2"><Select name="classId" label="Class" options={classes} defaultValue={assignment?.classId || ""} /><Select name="subjectId" label="Subject" options={subjects} defaultValue={assignment?.subjectId || ""} /><Input name="title" label="Title" defaultValue={assignment?.title || ""} required /><Input name="dueDate" label="Due date" type="date" defaultValue={assignment?.dueDate?.toISOString().slice(0,10) || ""} /><Input name="maxPoints" label="Max points" type="number" defaultValue={String(assignment?.maxPoints || 100)} required /><label className="text-sm font-semibold text-ink">Status<select name="status" defaultValue={assignment?.status || "DRAFT"} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="CLOSED">Closed</option></select></label></div><label className="block text-sm font-semibold text-ink">Description<textarea name="description" defaultValue={assignment?.description || ""} rows={5} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm" /></label><button className="rounded-md bg-ink px-5 py-3 text-sm font-bold text-white">Save Assignment</button></form>; }
function Select({ name, label, options, defaultValue }: { name: string; label: string; options: { id: string; name: string }[]; defaultValue: string }) { return <label className="text-sm font-semibold text-ink">{label}<select name={name} required defaultValue={defaultValue} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm"><option value="">Choose {label.toLowerCase()}</option>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>; }
function Input({ name, label, type = "text", defaultValue, required }: { name: string; label: string; type?: string; defaultValue: string; required?: boolean }) { return <label className="text-sm font-semibold text-ink">{label}<input name={name} type={type} defaultValue={defaultValue} required={required} className="mt-2 w-full rounded-md border border-line px-3 py-3 text-sm" /></label>; }
