"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { canManageLms } from "@/lib/rbac";
import { getRequiredCurrentUser } from "@/lib/session";
import { tenantFilter } from "@/lib/tenant";

function text(formData: FormData, key: string) { return String(formData.get(key) || "").trim(); }
async function context() { const user = await getRequiredCurrentUser(); if (!canManageLms(user.role)) throw new Error("Not authorized to manage LMS"); const schoolId = tenantFilter(user).schoolId; return { user, schoolId }; }
async function assertClass(user: Awaited<ReturnType<typeof getRequiredCurrentUser>>, schoolId: string, classId: string) { const klass = await db.class.findFirst({ where: { id: classId, schoolId, ...(user.role === "TEACHER" ? { id: { in: user.assignedClassIds } } : {}) } }); if (!klass) throw new Error("Class not available"); }
async function assertSubject(schoolId: string, subjectId: string) { const subject = await db.subject.findFirst({ where: { id: subjectId, schoolId } }); if (!subject) throw new Error("Subject not found"); }

export async function createSubject(formData: FormData) { const { schoolId } = await context(); await db.subject.create({ data: { schoolId, name: text(formData, "name"), code: text(formData, "code") || null, description: text(formData, "description") || null, isGed: formData.get("isGed") === "on" } }); revalidatePath("/dashboard/lms"); redirect("/dashboard/lms?saved=subject"); }
export async function updateSubject(formData: FormData) { const { schoolId } = await context(); const id = text(formData, "id"); const subject = await db.subject.findFirst({ where: { id, schoolId } }); if (!subject) throw new Error("Subject not found"); await db.subject.update({ where: { id }, data: { name: text(formData, "name"), code: text(formData, "code") || null, description: text(formData, "description") || null, isGed: formData.get("isGed") === "on" } }); revalidatePath("/dashboard/lms"); redirect("/dashboard/lms?saved=subject"); }
export async function deleteSubjectSafely(formData: FormData) { const { schoolId } = await context(); const id = text(formData, "id"); const subject = await db.subject.findFirst({ where: { id, schoolId }, include: { _count: { select: { lessons: true, assignments: true, exams: true } } } }); if (!subject) throw new Error("Subject not found"); if (subject._count.lessons + subject._count.assignments + subject._count.exams > 0) redirect("/dashboard/lms?error=subjectDependencies"); await db.subject.delete({ where: { id } }); revalidatePath("/dashboard/lms"); redirect("/dashboard/lms?saved=subjectDeleted"); }

export async function createLesson(formData: FormData) { const { user, schoolId } = await context(); const classId = text(formData, "classId"); const subjectId = text(formData, "subjectId"); await assertClass(user, schoolId, classId); await assertSubject(schoolId, subjectId); await db.lesson.create({ data: { schoolId, classId, subjectId, title: text(formData, "title"), description: text(formData, "description") || null, content: text(formData, "content") || null, createdById: user.id } }); revalidatePath("/dashboard/lms"); redirect("/dashboard/lms?saved=lesson"); }
export async function updateLesson(formData: FormData) { const { user, schoolId } = await context(); const id = text(formData, "id"); const classId = text(formData, "classId"); const subjectId = text(formData, "subjectId"); const lesson = await db.lesson.findFirst({ where: { id, schoolId } }); if (!lesson) throw new Error("Lesson not found"); await assertClass(user, schoolId, classId); await assertSubject(schoolId, subjectId); await db.lesson.update({ where: { id }, data: { classId, subjectId, title: text(formData, "title"), description: text(formData, "description") || null, content: text(formData, "content") || null } }); revalidatePath("/dashboard/lms"); revalidatePath(`/dashboard/lms/${id}`); redirect(`/dashboard/lms/${id}?saved=lesson`); }
export async function deleteLesson(formData: FormData) { const { user, schoolId } = await context(); const id = text(formData, "id"); const lesson = await db.lesson.findFirst({ where: { id, schoolId } }); if (!lesson) throw new Error("Lesson not found"); await assertClass(user, schoolId, lesson.classId); await db.lesson.delete({ where: { id } }); revalidatePath("/dashboard/lms"); redirect("/dashboard/lms?saved=lessonDeleted"); }
