import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { deleteClassSafely } from "@/app/dashboard/classes/actions";
import { db } from "@/lib/db";
import { canManageClasses } from "@/lib/rbac";
import { getRequiredCurrentUser } from "@/lib/session";
import { tenantFilter } from "@/lib/tenant";

export default async function ClassDetailPage({ params, searchParams }: { params: Promise<{ classId: string }>; searchParams?: Promise<{ error?: string; saved?: string }> }) {
  const { classId } = await params; const query = await searchParams; const user = await getRequiredCurrentUser(); const schoolId = tenantFilter(user).schoolId;
  const klass = await db.class.findFirst({ where: { id: classId, schoolId, ...(user.role === "TEACHER" ? { id: { in: user.assignedClassIds } } : {}) }, include: { teacher: true, enrollments: { where: { status: "ACTIVE" }, include: { student: true }, orderBy: { student: { studentNumber: "asc" } } }, lessons: true, assignments: true, exams: true } });
  if (!klass) notFound(); const canManage = canManageClasses(user.role);
  return <div className="space-y-6 pb-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><PageHeader eyebrow="Class" title={klass.name} description={`${klass.academicYear} · ${klass.teacher?.name || "Unassigned"} · ${klass.room || "No room"}`} />{canManage ? <div className="flex gap-2"><Link href={`/dashboard/classes/${klass.id}/edit`} className="rounded-md bg-primary px-4 py-3 text-sm font-bold text-on-primary">Edit</Link><Link href={`/dashboard/enrollments?classId=${klass.id}`} className="rounded-md border border-hairline-strong bg-canvas px-4 py-3 text-sm font-bold text-ink hover:bg-surface">Manage roster</Link></div> : null}</div>{query?.saved ? <div className="rounded-lg border border-success/30 bg-tint-mint p-4 text-sm font-semibold text-success">Class saved.</div> : null}{query?.error === "dependencies" ? <div className="rounded-lg border border-error/30 bg-tint-rose p-4 text-sm font-semibold text-error">This class has dependent records, so safe delete was blocked.</div> : null}<section className="grid gap-4 md:grid-cols-4">{[["Students", klass.enrollments.length], ["Lessons", klass.lessons.length], ["Assignments", klass.assignments.length], ["Exams", klass.exams.length]].map(([label, value]) => <div key={label} className="rounded-lg border border-hairline bg-canvas p-5 shadow-soft"><p className="text-sm text-slate">{label}</p><p className="mt-2 text-2xl font-bold text-ink">{value}</p></div>)}</section><section className="rounded-lg border border-hairline bg-canvas p-5 shadow-soft"><h2 className="text-lg font-semibold text-ink">Active roster</h2><div className="mt-4 divide-y divide-line">{klass.enrollments.map(e => <p key={e.id} className="py-3 text-sm text-slate"><span className="font-semibold text-ink">{e.student.preferredName || e.student.legalName || e.student.studentNumber}</span> · {e.student.studentNumber}</p>)}{klass.enrollments.length === 0 ? <p className="text-sm text-slate">No active roster records.</p> : null}</div></section>{canManage ? <form action={deleteClassSafely}><input type="hidden" name="id" value={klass.id} /><button className="rounded-md border border-error/45 px-4 py-2 text-sm font-bold text-error">Delete safely if unused</button></form> : null}</div>;
}
