"use server";

import { AssignmentStatus } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { canManageGrades } from "@/lib/rbac";
import { getRequiredCurrentUser } from "@/lib/session";
import { tenantFilter } from "@/lib/tenant";

function text(formData: FormData, key: string) { return String(formData.get(key) || "").trim(); }
async function ctx() { const user = await getRequiredCurrentUser(); if (!canManageGrades(user.role)) throw new Error("Not authorized to manage assignments"); const schoolId = tenantFilter(user).schoolId; return { user, schoolId }; }
async function assertClass(user: Awaited<ReturnType<typeof getRequiredCurrentUser>>, schoolId: string, classId: string) { const klass = await db.class.findFirst({ where: { id: classId, schoolId, ...(user.role === "TEACHER" ? { id: { in: user.assignedClassIds } } : {}) } }); if (!klass) throw new Error("Class not available"); }
async function assertSubject(schoolId: string, subjectId: string) { const subject = await db.subject.findFirst({ where: { id: subjectId, schoolId } }); if (!subject) throw new Error("Subject not found"); }
function dueDate(formData: FormData) { const raw = text(formData, "dueDate"); return raw ? new Date(raw) : null; }
function maxPoints(formData: FormData) { return Math.max(1, Number(text(formData, "maxPoints") || 100)); }
function status(formData: FormData) { return (text(formData, "status") || "DRAFT") as AssignmentStatus; }

export async function createAssignment(formData: FormData) { const { user, schoolId } = await ctx(); const classId = text(formData, "classId"); const subjectId = text(formData, "subjectId"); await assertClass(user, schoolId, classId); await assertSubject(schoolId, subjectId); await db.assignment.create({ data: { schoolId, classId, subjectId, title: text(formData, "title"), description: text(formData, "description") || null, dueDate: dueDate(formData), maxPoints: maxPoints(formData), status: status(formData), createdById: user.id } }); revalidatePath("/dashboard/assignments"); redirect("/dashboard/assignments?saved=created"); }
export async function updateAssignment(formData: FormData) { const { user, schoolId } = await ctx(); const id = text(formData, "id"); const existing = await db.assignment.findFirst({ where: { id, schoolId } }); if (!existing) throw new Error("Assignment not found"); const classId = text(formData, "classId"); const subjectId = text(formData, "subjectId"); await assertClass(user, schoolId, classId); await assertSubject(schoolId, subjectId); await db.assignment.update({ where: { id }, data: { classId, subjectId, title: text(formData, "title"), description: text(formData, "description") || null, dueDate: dueDate(formData), maxPoints: maxPoints(formData), status: status(formData) } }); revalidatePath("/dashboard/assignments"); revalidatePath(`/dashboard/assignments/${id}`); redirect(`/dashboard/assignments/${id}?saved=updated`); }
export async function deleteAssignment(formData: FormData) { const { schoolId } = await ctx(); const id = text(formData, "id"); const assignment = await db.assignment.findFirst({ where: { id, schoolId } }); if (!assignment) throw new Error("Assignment not found"); await db.assignment.delete({ where: { id } }); revalidatePath("/dashboard/assignments"); redirect("/dashboard/assignments?saved=deleted"); }
export async function saveAssignmentGrades(formData: FormData) { const { user, schoolId } = await ctx(); const assignmentId = text(formData, "assignmentId"); const assignment = await db.assignment.findFirst({ where: { id: assignmentId, schoolId } }); if (!assignment) throw new Error("Assignment not found"); await assertClass(user, schoolId, assignment.classId); const students = await db.student.findMany({ where: { schoolId, enrollments: { some: { classId: assignment.classId, status: "ACTIVE" } } }, select: { id: true } }); for (const student of students) { const pointsRaw = text(formData, `points_${student.id}`); const feedback = text(formData, `feedback_${student.id}`); if (!pointsRaw && !feedback) continue; const points = pointsRaw ? Number(pointsRaw) : null; if (points !== null && (points < 0 || points > assignment.maxPoints)) throw new Error("Points exceed max points"); await db.assignmentSubmission.upsert({ where: { schoolId_assignmentId_studentId: { schoolId, assignmentId, studentId: student.id } }, create: { schoolId, assignmentId, studentId: student.id, status: points === null ? "SUBMITTED" : "GRADED", points, feedback: feedback || null, gradedById: user.id, gradedAt: points === null ? null : new Date() }, update: { status: points === null ? "SUBMITTED" : "GRADED", points, feedback: feedback || null, gradedById: user.id, gradedAt: points === null ? null : new Date() } }); } revalidatePath(`/dashboard/assignments/${assignmentId}`); redirect(`/dashboard/assignments/${assignmentId}?saved=grades`); }
