import { PageHeader } from "@/components/page-header";
import { createExam } from "@/app/dashboard/exams/actions";
import { getVisibleClassesForLearning, getVisibleSubjects } from "@/lib/lms";
import { canManageGrades } from "@/lib/rbac";
import { getRequiredCurrentUser } from "@/lib/session";

export default async function NewExamPage() { const user = await getRequiredCurrentUser(); if (!canManageGrades(user.role)) return <PageHeader eyebrow="Exams" title="Not authorized" description="You cannot create exams." />; const [classes, subjects] = await Promise.all([getVisibleClassesForLearning(user), getVisibleSubjects(user)]); return <div className="space-y-6 pb-10"><PageHeader eyebrow="Exams" title="Create Exam" description="Schedule or draft a class exam." /><ExamForm action={createExam} classes={classes} subjects={subjects} /></div>; }
export function ExamForm({ action, classes, subjects, exam }: { action: (formData: FormData) => Promise<void>; classes: { id: string; name: string }[]; subjects: { id: string; name: string }[]; exam?: { id: string; classId: string; subjectId: string; title: string; description: string | null; examDate: Date | null; maxMarks: number; status: string } }) { return <form action={action} className="space-y-4 rounded-lg border border-hairline bg-canvas p-5 shadow-soft"><input type="hidden" name="id" value={exam?.id || ""} /><div className="grid gap-4 sm:grid-cols-2"><Select name="classId" label="Class" options={classes} defaultValue={exam?.classId || ""} /><Select name="subjectId" label="Subject" options={subjects} defaultValue={exam?.subjectId || ""} /><Input name="title" label="Title" defaultValue={exam?.title || ""} required /><Input name="examDate" label="Exam date" type="date" defaultValue={exam?.examDate?.toISOString().slice(0,10) || ""} /><Input name="maxMarks" label="Max marks" type="number" defaultValue={String(exam?.maxMarks || 100)} required /><label className="text-sm font-semibold text-ink">Status<select name="status" defaultValue={exam?.status || "DRAFT"} className="mt-2 w-full rounded-md border border-hairline px-3 py-3 text-sm"><option value="DRAFT">Draft</option><option value="SCHEDULED">Scheduled</option><option value="COMPLETED">Completed</option></select></label></div><label className="block text-sm font-semibold text-ink">Description<textarea name="description" defaultValue={exam?.description || ""} rows={5} className="mt-2 w-full rounded-md border border-hairline px-3 py-3 text-sm" /></label><button className="rounded-md bg-ink px-5 py-3 text-sm font-bold text-on-dark">Save Exam</button></form>; }
function Select({ name, label, options, defaultValue }: { name: string; label: string; options: { id: string; name: string }[]; defaultValue: string }) { return <label className="text-sm font-semibold text-ink">{label}<select name={name} required defaultValue={defaultValue} className="mt-2 w-full rounded-md border border-hairline px-3 py-3 text-sm"><option value="">Choose {label.toLowerCase()}</option>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>; }
function Input({ name, label, type = "text", defaultValue, required }: { name: string; label: string; type?: string; defaultValue: string; required?: boolean }) { return <label className="text-sm font-semibold text-ink">{label}<input name={name} type={type} defaultValue={defaultValue} required={required} className="mt-2 w-full rounded-md border border-hairline px-3 py-3 text-sm" /></label>; }
